### ISSUE TITLE
Error while generating required QSC certificates

### ISSUE THREAD

**Issue by RohitArora7** [open-quantum-safe/oqs-demos#150]
Hi, I am getting the following error while generating all required QSC certificates

```
ubuntu@ubuntu:~/oqs-demos/nginx/fulltest$ python3 genconfig.py
. > /tmp/opt/openssl/apps/openssl req -x509 -new -newkey rsa:4096 -keyout root/CA.key -out root/CA.crt -nodes -subj /CN=oqstest_CA -days 500 -config /tmp/opt/openssl/apps/openssl.cnf
New root cert residing in root/CA.crt.
. > /tmp/opt/openssl/apps/openssl ecparam -name prime256v1 -out pki/prime256v1.pem
Can't open pki/prime256v1.pem for writing, No such file or directory
0:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('pki/prime256v1.pem','w')
0:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:

Traceback (most recent call last):
  File "genconfig.py", line 197, in <module>
    main()
  File "genconfig.py", line 193, in main
    gen_cert(sig)
  File "genconfig.py", line 63, in gen_cert
    common.run_subprocess([OPENSSL, "ecparam", "-name", "prime256v1", "-out", os.path.join(PKIPATH, "prime256v1.pem")])
  File "/home/ubuntu/oqs-demos/nginx/fulltest/common.py", line 47, in run_subprocess
    assert False, "Got unexpected return code {}".format(result.returncode)
AssertionError: Got unexpected return code 1
```

**Comment by baentsch** [comment]
The error message 

> Can't open pki/prime256v1.pem for writing, No such file or directory

shows the issue: The directory 'pki' does not exist (created e.g., at https://github.com/open-quantum-safe/oqs-demos/blob/ee6b4110ce4762224cf12ed2d379769b917ff683/nginx/fulltest/package.sh#L15). Will do a doc update.
